/**
* StoryClient.java
* Assignment: Final Project
* Purpose: To let us have some experience with actual coding, rather than
* just systematically fulfilling assignments through which we are
* walked step by step.
* @version 06/03/15
* @author Sierramatice Karras
*/

import java.awt.*;
import java.io.*;
import java.util.*;

public class StoryClient {
   
   public static void main (String[] args) throws FileNotFoundException {
      intro();
      Scanner console = new Scanner(System.in);
      ArrayList<Story> storyInfo = new ArrayList<Story>();
      String genre = genre(console);
      System.out.println("How would you like to generate your story data? (input/random)");
      if (console.next().equalsIgnoreCase("input")){
         boolean more = true;
         while (more) {
            userInput(console, storyInfo, genre);
            System.out.println("Do you want more information? (yes/no)");
            String answer = console.next();
            if (answer.charAt(0) != 'y' && answer.charAt(0) != 'Y') {
               more = false;
            }
         }
      } else {
         totalRandom(genre, storyInfo);
      }
      output(storyInfo, genre);
   }
   
   /* @param the Scanner console
   * @return the String containing the genre of the story
   * asks the user what genre of story they would like to generate, returns the anwer as a String
   */
   public static String genre(Scanner console) {
      String genre;
      System.out.println("What genre of story do you want? \n(sci-fi/mystery/fantasy/realistic/"
            + "historical/superhero/any/random)");
      genre = console.next();
      if (genre.equalsIgnoreCase("random")){
         genre = randomGenre();
      }
      return genre;
   }
   
   /* @param the String containing the genre of the story, 
   * @return nothing
   * randomly generates every story element without user input, creating and storing two
   * character, one setting, one plot, and four different props 
   */
   public static void totalRandom(String genre, ArrayList<Story> storyInfo) throws 
      FileNotFoundException {
      Character person = new Character("either", genre, "human");
      Character person2 = new Character("either", genre, "creature");
      Setting local = new Setting(genre);
      Plot tale = new Plot();
      Props thing = new Props(genre, "pet", "yes");
      Props thing2 = new Props(genre, "accessory", "no");
      Props thing3 = new Props(genre, "weapon", "no");
      Props thing4 = new Props(genre, "random", "no");
      storyInfo.add(person);
      storyInfo.add(person2);
      storyInfo.add(local);
      storyInfo.add(tale);
      storyInfo.add(thing);
      storyInfo.add(thing2);
      storyInfo.add(thing3);
      storyInfo.add(thing4);
   }
   
   /* @param nothing
   * @return a String containing a randomly selected genre
   * picks a random genre from the file and returns it.
   */
   public static String randomGenre() {
      String genre;
      ArrayList<String> genres = new ArrayList<String>();
      genres.add("sci-fi"); 
      genres.add("mystery");
      genres.add("fantasy");
      genres.add("superhero");
      genres.add("historical");
      genres.add("realistic");
      int numb = (int)(Math.random() * genres.size());
      genre =  genres.get(numb);
      return genre;
   }
   
   /* @param nothing
   * @return nothing
   * @see a greeting to the user, and a short introduction to the program
   * prints a short introduction to the program onto the console
   */
   public static void intro() {
      System.out.println("Hello, and welcome to the magical and mysterious"
         + " story generator!");
      System.out.println("Choose genre, and data to be generated and then create stories to "
         + "your heart's content...");
      System.out.println();
   }
   
   /* @param the Scanner containing the console, the  ArrayList of Stories that stores the
   * information generated by the program, and the String containing the genre
   * @return nothing
   * takes basic information about what data the user wants and stores it in an ArrayList
   * [inforamtion requseted, type of character/ item, gender/ sentiance], then generates that 
   * information and stores it in the ArrayList storyInfo
   */
   public static void userInput(Scanner console, ArrayList<Story> storyInfo, String genre) throws
      FileNotFoundException {
      ArrayList<String> userData = new ArrayList<String>(4);
      System.out.println("What infomation do you want? (character/setting/plot/item)");
      userData.add(console.next());
      if (userData.get(0).equalsIgnoreCase("character")){
         System.out.println("Type? (human/creature)");
         userData.add(console.next());
         System.out.println("Gender? (male/female/either)");
         userData.add(console.next());
      } else if (userData.get(0).equalsIgnoreCase("item")){
         System.out.println("What type? (weapon/accessory/pet/random)");
         userData.add(console.next());
         System.out.println("Sentiance? (yes/no)");
         userData.add(console.next());
      } 
      System.out.println();
      if (userData.get(0).equalsIgnoreCase("character")){
         Character person = new Character(userData.get(2), genre, userData.get(1));
         storyInfo.add(person);
      } else if (userData.get(0).equalsIgnoreCase("setting")){
         Setting local = new Setting (genre);
         storyInfo.add(local);
      } else if (userData.get(0).equalsIgnoreCase("plot")){
         Plot tale = new Plot ();
         storyInfo.add(tale);
      } else if (userData.get(0).equalsIgnoreCase("item")) {
         Props thing = new Props(genre, userData.get(1), userData.get(2));
         storyInfo.add(thing);
      }
   }
   
   /* @param the ArrayList of Stories containing all the information generated by the program,
   * and a String containing the genre of the story
   * @return nothing
   * @see prints out headings and information for all the generated information
   * prints the toString methods of all the classes of information collected
   */   
   public static void output(ArrayList<Story> info, String genre) {
      System.out.println();
      for (int i = 0; i<= 40; i++){
         System.out.print("--");
      }
      System.out.println();
      genre = genre.substring(0, 1).toUpperCase() + genre.substring(1).toLowerCase();
      System.out.println("Genre: " + genre);
      System.out.println();
      for (int i = 0; i < info.size(); i++) {
         System.out.println(info.get(i));
         System.out.println();
      }
   }
}